# Generated by Django 5.1 on 2025-02-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_artist_biography_remove_artist_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('artist', 'Artist'), ('admin', 'Admin'), ('customer', 'customer')], default='artist', max_length=15),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('artist', 'Artist'), ('admin', 'Admin')], max_length=50),
        ),
    ]
